.if t .wh -1.3i ^B
.nr ^l \n(.l
.ad b
'\"	# Start an argument description
.de AP
.ie !"\\$4"" .TP \\$4
.el \{\
.   ie !"\\$2"" .TP \\n()Cu
.   el          .TP 15
.\}
.ta \\n()Au \\n()Bu
.ie !"\\$3"" \{\
\&\\$1	\\fI\\$2\\fP	(\\$3)
.\".b
.\}
.el \{\
.br
.ie !"\\$2"" \{\
\&\\$1	\\fI\\$2\\fP
.\}
.el \{\
\&\\fI\\$1\\fP
.\}
.\}
..
.de BS
.br
.mk ^y
.nr ^b 1u
.if n .nf
.if n .ti 0
.if n \l'\\n(.lu\(ul'
.if n .fi
..
'\"	# BE - end boxed text (draw box now)
.de BE
.nf
.ti 0
.mk ^t
.ie n \l'\\n(^lu\(ul'
.el \{\
.\"	Draw four-sided box normally, but don't draw top of
.\"	box if the box started on an earlier page.
.ie !\\n(^b-1 \{\
\h'-1.5n'\L'|\\n(^yu-1v'\l'\\n(^lu+3n\(ul'\L'\\n(^tu+1v-\\n(^yu'\l'|0u-1.5n\(ul'
.\}
.el \}\
\h'-1.5n'\L'|\\n(^yu-1v'\h'\\n(^lu+3n'\L'\\n(^tu+1v-\\n(^yu'\l'|0u-1.5n\(ul'
.\}
.\}
.fi
.br
.nr ^b 0
..
'\"	# VS - start vertical sidebar
'\"	# ^Y = starting y location
'\"	# ^v = 1 (for troff;  for nroff this doesn't matter)
..
.TH ft_scheduler_create, 1
.SH NAME
ft_scheduler_create, ft_scheduler_start \- create and start a new scheduler
.SS SYNOPSIS

.Sp
.nf
\fB#include\fR <fthread.h>

ft_scheduler_t \fBft_scheduler_create\fR (void);

int \fBft_scheduler_start\fR (ft_scheduler_t sched);

.Sp
.fi
.SS DESCRIPTION

\fBft_scheduler_create\fR returns a new scheduler that will run the threads
created in it, using \fBft_thread_create\fR.

The new scheduler \fBsched\fR starts running when the function \fBft_scheduler_start\fR
is called.
.SS RETURN VALUES


On success \fBft_scheduler_create\fR returns the new scheduler; \fBNULL\fR is returned otherwise.
On success the value 0 is returned by \fBft_scheduler_start\fR and a non-zero error 
code is returned otherwise.

.SS ERRORS


.RS 3
.TP
\&\fBNULL\fR 
The scheduler cannot be created.
.RE


.RS 3
.TP
\&\fBBADCREATE\fR 
The scheduler \fBsched\fR
is not correctly created when started.
.RE


.SS SEE ALSO

\fBft_thread_create\fR (3).

.SH AUTHOR


